---
- name: Deploy Application
  hosts: production
  become: yes  # Enable privilege escalation
  tasks:
    - name: Check if Java is installed
      ansible.builtin.command: java -version
      ignore_errors: yes
      register: java_check

    - name: Install Java if not present
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present
        update_cache: yes
      when: java_check.rc != 0

    - name: Copy application jar to the server
      ansible.builtin.copy:
        src: target/spring-petclinic-3.3.0-SNAPSHOT.jar
        dest: /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Start the application
      ansible.builtin.shell: |
        nohup java -jar /home/ubuntu/spring-petclinic-3.3.0-SNAPSHOT.jar --server.port={{ 8081 }} > app.log 2>&1 &
      args:
        executable: /bin/bash
